### ISSUE TITLE
Release build: upload staged artifacts

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon-build-tools#1034]
Upload staged artifacts of build like we do for Helidon. For example, add a step like this to the release job:

```
      - name: Upload Staged Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: io-helidon-build-tools-artifacts-${{ github.ref_name }}
          path: target/nexus-staging/
          retention-days: 90
```
