### ISSUE TITLE
Sitegen-Maven-Plugin: Maven properties are no longer resolved in sitegen.yaml

### ISSUE THREAD

**Issue by ghillert** [helidon-io/helidon-build-tools#1065]
It looks like in the `3.x` versions, Maven properties are no longer resolved in `sitegen.yaml`. The following was working previously with the `2.x` versions of the plugin: 

```
engine:
  asciidoctor:
    images-dir: "./images"
    libraries:
      - "asciidoctor-diagram"
    attributes:
...
      version-coherence-maven: "${revision}"
      version-coherence-spring: "${project.version}"
      version-coherence: "${coherence.version}"
...
```

While the attribute itself, e.g. `version-coherence-maven` is set, the Maven property is not resolved but rather passed on as a string `${revision}`.
