### ISSUE TITLE
Helidon Sitegen Maven Plugin: images folder is not always copied

### ISSUE THREAD

**Issue by ghillert** [helidon-io/helidon-build-tools#949]
I noticed a weird issue when upgrade the Coherence Spring website to the latest `3.0.5` release of the Helidon Sitegen Maven Plugin. I had a website that was using no images in the Asciidoc directly. Just the logo and favicon, e.g.:

```
    navigation:
      type: "ROOT"
      title: "Oracle Coherence Spring"
      glyph:
        type: "image"
        value: "images/logo.svg"
```

See: https://github.com/coherence-community/coherence-spring/blob/main/coherence-spring-site/sitegen.yaml

In that case, the images folder was not copied over to `/target/site/` and the logo was not displayed. However, as soon as I added an image to one of the AsciiDoc pages, everything inside the images got copied over and worked as expected.

This works (The only image in my adoc files):

```
[CARD]
.Quickstart
[image=logo-with-padding.svg,link=refdocs/reference/html/quickstart.html,link-type=url]
--
Chapter of the Reference Guide.
--
```

This will fail, no images folder copied. Navigation logo missing.

```
[CARD]
.Quickstart
[icon=power_settings_new,link=refdocs/reference/html/quickstart.html,link-type=url]
--
Chapter of the Reference Guide.
--
```

See: https://github.com/coherence-community/coherence-spring/blob/main/coherence-spring-site/docs/about/01_overview.adoc?plain=1
